version: '3'

networks:
  laravel:

services:
  app:
    build:
      context: .
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - ${NGX_PORT}:80
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: ${APP_NAME}-php
    volumes:
      - ./src:/var/www/html:delegated
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - ${PHP_PORT}:9000
      - ${PHPXDEBUG_PORT}:9003
    networks:
      - laravel

  mysql:
    image: mysql:5.7.29
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3307:3306
    volumes:
      - ./mysql_storage:/var/lib/mysql
    environment:
      MYSQL_DATABASE: demo_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: ${APP_NAME}-composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: laravel
    entrypoint: ['composer', '--ignore-platform-reqs']
    networks:
      - laravel

  npm:
    image: node:18.4.0-alpine
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - laravel

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: ${APP_NAME}-artisan
    volumes:
      - ./src:/var/www/html:delegated
    working_dir: /var/www/html
    user: laravel
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel
  
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - ${MAIL_HOG_SMTP_PORT}:1025
      - ${MAIL_HOG_HTTP_PORT}:8025
    networks:
      - laravel